bot:
  host_service: zeabur.com
  lang: python
  name: twitch-python
  package_manager: pip
  start_cmd: python3 ./src/main.py
  type: twitch
docker:
  cmds:
    build: docker build -t botway-local/twitch-python .
    run: docker run -it botway-local/twitch-python
  enable_buildkit: true
  image: botway-local/twitch-python
