bot:
  host_service: zeabur.com
  lang: cpp
  name: discord-cpp
  package_manager: cmake
  start_cmd: cd build; make -j; ./discord-cpp
  type: discord
docker:
  cmds:
    build: docker build -t botway-local/discord-cpp .
    run: docker run -it botway-local/discord-cpp
  enable_buildkit: true
  image: botway-local/discord-cpp
