bot:
  host_service: zeabur.com
  lang: ruby
  name: discord-ruby
  package_manager: bundler
  start_cmd: bundle exec ruby src/main.rb
  type: discord
docker:
  cmds:
    build: docker build -t botway-local/discord-ruby .
    run: docker run -it botway-local/discord-ruby
  enable_buildkit: true
  image: botway-local/discord-ruby
