bot:
  host_service: zeabur.com
  lang: deno
  name: twitch-deno
  package_manager: deno
  start_cmd: deno task run
  type: twitch
docker:
  cmds:
    build: docker build -t botway-local/twitch-deno .
    run: docker run -it botway-local/twitch-deno
  enable_buildkit: true
  image: botway-local/twitch-deno
