bot:
  host_service: railway.app
  lang: dart
  name: discord-dart
  package_manager: pub
  start_cmd: dart run src/main.dart
  type: discord
docker:
  cmds:
    build: docker build -t botway-local/discord-dart .
    run: docker run -it botway-local/discord-dart
  enable_buildkit: true
  image: botway-local/discord-dart
