name: "dart"
description: My Awesome Discord (Dart) Bot
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  botway_dart: ^0.1.1
  nyxx: ^4.1.0
  nyxx_commands: ^4.3.0
  nyxx_commander: ^3.0.0
  nyxx_extensions: ^3.0.0
  nyxx_interactions: ^4.2.1
  nyxx_lavalink: ^3.1.0
  nyxx_pagination: ^2.3.0
  nyxx_sharding: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
