bot:
  host_service: railway.app
  lang: kotlin
  name: discord-kotlin
  package_manager: gradle
  start_cmd: ./gradlew run
  type: discord
docker:
  cmds:
    build: docker build -t botway-local/discord-kotlin .
    run: docker run -it botway-local/discord-kotlin
  enable_buildkit: true
  image: botway-local/discord-kotlin
