name: "dart"
description: My Awesome Telegram (Dart) Bot
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  botway_dart: ^0.1.1
  teledart: ^0.3.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
