bot:
  host_service: zeabur.com
  lang: rust
  name: discord-rust
  package_manager: cargo
  start_cmd: cargo run src/main.rs
  type: discord
docker:
  cmds:
    build: docker build -t botway-local/discord-rust .
    run: docker run -it botway-local/discord-rust
  enable_buildkit: true
  image: botway-local/discord-rust
