bot:
  host_service: zeabur.com
  lang: java
  name: twitch-java
  package_manager: gradle
  start_cmd: ./gradlew run
  type: twitch
docker:
  cmds:
    build: docker build -t botway-local/twitch-java .
    run: docker run -it botway-local/twitch-java
  enable_buildkit: true
  image: botway-local/twitch-java
