bot:
  host_service: zeabur.com
  lang: java
  name: telegram-java
  package_manager: gradle
  start_cmd: ./gradlew run
  type: telegram
docker:
  cmds:
    build: docker build -t botway-local/telegram-java .
    run: docker run -it botway-local/telegram-java
  enable_buildkit: true
  image: botway-local/telegram-java
